import * as fs from 'node:fs';
import * as path from 'node:path';
import { LeadScoringResult } from '../scoring/rubric-engine.js';
import { rootLogger } from '@atlas/observability';

export interface ArtifactMeta {
  name: string;
  mimeType: string;
  filePath: string;
  sizeBytes: number;
}

export interface ArtifactMetadataWriter {
  record(input: ArtifactMeta & { taskId: string; runId?: string }): Promise<unknown>;
}

export class ArtifactService {
  private readonly storageDir: string;

  constructor(storageDir = './data/artifacts', private metadataWriter?: ArtifactMetadataWriter) {
    this.storageDir = path.resolve(storageDir);
    if (!fs.existsSync(this.storageDir)) {
      fs.mkdirSync(this.storageDir, { recursive: true });
    }
  }

  public save(name: string, content: string, mimeType = 'text/plain'): ArtifactMeta {
    const fullPath = this.resolveArtifactPath(name);
    const dir = path.dirname(fullPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(fullPath, content, 'utf-8');
    const sizeBytes = Buffer.byteLength(content, 'utf-8');
    rootLogger.info(`Artifact saved: ${name} (${sizeBytes} bytes)`);

    return {
      name,
      mimeType,
      filePath: fullPath,
      sizeBytes
    };
  }

  public read(name: string): string | null {
    let fullPath: string;
    try {
      fullPath = this.resolveArtifactPath(name);
    } catch {
      return null;
    }
    if (!fs.existsSync(fullPath)) return null;
    return fs.readFileSync(fullPath, 'utf-8');
  }

  public async recordMetadata(
    meta: ArtifactMeta,
    context: { taskId: string; runId?: string }
  ): Promise<void> {
    if (!this.metadataWriter) return;
    await this.metadataWriter.record({ ...meta, ...context });
  }

  private resolveArtifactPath(name: string): string {
    if (!name || path.isAbsolute(name)) {
      throw new Error('Artifact path must be a relative name inside the storage root.');
    }

    const fullPath = path.resolve(this.storageDir, name);
    const relativePath = path.relative(this.storageDir, fullPath);
    if (
      relativePath === '..' ||
      relativePath.startsWith(`..${path.sep}`) ||
      path.isAbsolute(relativePath)
    ) {
      throw new Error('Artifact path must remain inside the storage root.');
    }

    return fullPath;
  }

  // 1. Generate gym_leads.csv
  public exportLeadsCsv(leads: LeadScoringResult[], filename = 'gym_leads.csv'): ArtifactMeta {
    const headers = ['Rank', 'Lead ID', 'Name', 'Total Score', 'Status', 'Recommendation'];
    const rows = leads.map(l => [
      l.rank,
      `"${l.leadId}"`,
      `"${l.name.replace(/"/g, '""')}"`,
      l.totalScore,
      l.status,
      `"${l.recommendation.replace(/"/g, '""')}"`
    ]);

    const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    return this.save(filename, csvContent, 'text/csv');
  }

  // 2. Generate lead_scoring_report.md
  public exportScoringReport(leads: LeadScoringResult[], filename = 'lead_scoring_report.md'): ArtifactMeta {
    const rubricVersions = [...new Set(leads.map(lead => lead.rubricVersion))];
    const rubricLabel = rubricVersions.length === 1 ? rubricVersions[0] : rubricVersions.join(', ');
    const tableRows = leads.map(l =>
      `| ${l.rank} | **${l.name}** | ${l.totalScore}/100 | \`${l.status.toUpperCase()}\` | ${l.recommendation} |`
    ).join('\n');

    const markdown = `# Lead Scoring & ICP Evaluation Report

> Generated by **Layla (Sales & Lead Scoring Specialist)** for ATLAS AI OS.
> Evaluation based on 10-dimension weighted rubric.
> Rubric version: ${rubricLabel || 'unknown'}

| Rank | Business Name | ICP Score | Status | Recommendation |
|:---:|:---|:---:|:---:|:---|
${tableRows}

---

## Evaluation Summary
- **Total Evaluated:** ${leads.length} leads
- **Qualified (Score >= 80):** ${leads.filter(l => l.status === 'qualified').length} leads
- **Needs Review (60-79):** ${leads.filter(l => l.status === 'needs_review').length} leads
- **Disqualified (< 60):** ${leads.filter(l => l.status === 'disqualified').length} leads
- **Incomplete evidence:** ${leads.filter(l => !l.evidenceComplete).length} leads
`;

    return this.save(filename, markdown, 'text/markdown');
  }

  // 3. Generate outreach_drafts.md
  public exportOutreachDrafts(
    drafts: Array<{ leadName: string; contactPerson: string; phone: string; pitchDraft: string }>,
    filename = 'outreach_drafts.md'
  ): ArtifactMeta {
    const entries = drafts.map((d, idx) => `
### ${idx + 1}. ${d.leadName}
- **Target Contact:** ${d.contactPerson} (\`${d.phone}\`)
- **Status:** \`DRAFT (Pending Approval)\`

\`\`\`text
${d.pitchDraft}
\`\`\`
`).join('\n---\n');

    const markdown = `# WhatsApp Outreach Copy Drafts (Top Candidates)

> Drafted by **Hermes (Content & Communication Specialist)**
> **Notice:** All drafts are for human review. No outbound messages have been sent.

${entries}
`;

    return this.save(filename, markdown, 'text/markdown');
  }
}
