'use client';

import React, { useState } from 'react';
import { FileText, Download, Eye, FileSpreadsheet } from 'lucide-react';

interface MockArtifact {
  name: string;
  type: 'csv' | 'markdown' | 'json';
  size: string;
  createdAt: string;
  preview: string;
}

const SAMPLE_ARTIFACTS: MockArtifact[] = [
  {
    name: 'gym_leads.csv',
    type: 'csv',
    size: '4.2 KB',
    createdAt: '2026-08-26 05:01',
    preview: 'Rank,Lead ID,Name,Total Score,Status,Recommendation\n1,"gym-1","Celebrity Fitness Palembang",96,qualified,"Top tier candidate..."'
  },
  {
    name: 'lead_scoring_report.md',
    type: 'markdown',
    size: '6.8 KB',
    createdAt: '2026-08-26 05:01',
    preview: '# Lead Scoring & ICP Evaluation Report\n\n| Rank | Business Name | ICP Score | Status |\n| 1 | Celebrity Fitness | 96/100 | QUALIFIED |'
  },
  {
    name: 'outreach_drafts.md',
    type: 'markdown',
    size: '8.1 KB',
    createdAt: '2026-08-26 05:01',
    preview: '# WhatsApp Outreach Copy Drafts\n\n### 1. Celebrity Fitness Palembang\nStatus: DRAFT (Pending Approval)...'
  }
];

export default function ArtifactsPage() {
  const [selected, setSelected] = useState<MockArtifact>(SAMPLE_ARTIFACTS[0]!);

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      <div>
        <h1 className="text-xl font-bold text-white tracking-tight">Artifacts & Deliverables</h1>
        <p className="text-xs text-gray-400">Structured outputs, CSV exports, evaluation reports, and communication drafts generated by agents.</p>
      </div>

      <div className="grid grid-cols-3 gap-6">
        {/* Artifact List */}
        <div className="space-y-3">
          {SAMPLE_ARTIFACTS.map((art) => (
            <div
              key={art.name}
              onClick={() => setSelected(art)}
              className={`p-4 rounded-xl border cursor-pointer transition-all ${
                selected.name === art.name
                  ? 'bg-indigo-600/20 border-indigo-500/40 text-white'
                  : 'bg-[#111827] border-gray-800 text-gray-300 hover:border-gray-700'
              }`}
            >
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-gray-800 text-indigo-400">
                  {art.type === 'csv' ? <FileSpreadsheet className="w-4 h-4" /> : <FileText className="w-4 h-4" />}
                </div>
                <div>
                  <h4 className="text-xs font-semibold">{art.name}</h4>
                  <p className="text-[10px] text-gray-400 font-mono">{art.size} • {art.createdAt}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Preview Panel */}
        <div className="col-span-2 p-6 bg-[#111827] border border-gray-800 rounded-xl flex flex-col justify-between space-y-4">
          <div>
            <div className="flex items-center justify-between pb-4 border-b border-gray-800">
              <div>
                <h3 className="text-sm font-bold text-white">{selected.name}</h3>
                <p className="text-[10px] text-gray-400 font-mono">Format: {selected.type.toUpperCase()} • Size: {selected.size}</p>
              </div>
              <button
                onClick={() => alert(`Downloading ${selected.name}...`)}
                className="px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-medium flex items-center gap-1.5 transition-all"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download</span>
              </button>
            </div>

            <div className="mt-4 p-4 rounded-lg bg-[#090d16] border border-gray-800 text-xs font-mono text-gray-300 overflow-x-auto h-96">
              <pre>{selected.preview}</pre>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
